admin_admin:
    resource: ./routes/admin/admin.yaml
    prefix: /admin

admin_department:
    resource: ./routes/admin/department/department.yaml
    prefix: /admin/department

admin_employee:
    resource: ./routes/admin/employee/employee.yaml
    prefix: /admin/employee

employee_employee:
    resource: ./routes/employee/employee.yaml
    prefix: /employee

admin_size:
    resource: './routes/admin/garment_size/size.yaml'
    prefix: /admin/size

admin_garment:
    resource: './routes/admin/garment_size/garment.yaml'
    prefix: /admin/garment

admin_garment_type:
    resource: './routes/admin/garment_size/garment_type.yaml'
    prefix: /admin/garmenttype

admin_garment_size:
    resource: './routes/admin/garment_size/garment_size.yaml'
    prefix: /admin/garmentsize

employee_garment_size:
    resource: './routes/employee/garment_size/garment_size.yaml'
    prefix: /employee/garmentsize

admin_request_employee:
    resource: './routes/admin/request_employee/request_employee.yaml'
    prefix: /admin/requestemployee

employee_request_employee:
    resource: './routes/employee/request_employee/request_employee.yaml'
    prefix: /employee/requestemployee

admin_request_employee_garment:
    resource: './routes/admin/request_employee/request_employee_garment.yaml'
    prefix: /admin/requestemployeegarment

employee_request_employee_garment:
    resource: './routes/employee/request_employee/request_employee_garment.yaml'
    prefix: /employee/requestemployeegarment
