<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAjqWLkd\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAjqWLkd/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAjqWLkd.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAjqWLkd\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerAjqWLkd\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'AjqWLkd',
    'container.build_id' => '801ed613',
    'container.build_time' => 1524663723,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAjqWLkd');
