<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUUK8r5I\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUUK8r5I/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUUK8r5I.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUUK8r5I\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerUUK8r5I\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'UUK8r5I',
    'container.build_id' => '1c918e36',
    'container.build_time' => 1524569392,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUUK8r5I');
