<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM4kxeKO\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM4kxeKO/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerM4kxeKO.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerM4kxeKO\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerM4kxeKO\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'M4kxeKO',
    'container.build_id' => '89e36471',
    'container.build_time' => 1524676240,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerM4kxeKO');
